name: Build

on:
  workflow_dispatch:
    inputs:

jobs:
  mod_file:
    runs-on: ubuntu-latest
    steps:
    - run: |
        git clone https://nao20010128nao:${{ secrets.GH_PAT }}@github.com/nao20010128nao/actions-playground taps/
        sed -E -i 's/[A-F0-9]+/'$(head -c5 /dev/urandom | xxd -p | tr '[:lower:]' '[:upper:]')/ taps/modification-test.txt
        git -C taps/ config user.name github-actions
        git -C taps/ config user.email github-actions@example.com
        git -C taps/ commit -am "$(cat taps/modification-test.txt)"
        git -C taps/ push
