name: Python test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install
      run: brew install expect
    - name: Run 1
      continue-on-error: true
      run: python3 -c 'import os; open(os.ctermid(), "w")'
    - name: Run 2
      continue-on-error: true
      run: unbuffer python3 -c 'import os; open(os.ctermid(), "w")'
