name: ytdl-patched build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:

jobs:
  nuitka:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, ubuntu]
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ytdl-patched/ytdl-patched
        ref: ytdlp
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        pip install -U git+https://github.com/Nuitka/Nuitka zopflipy websockets pyyaml python-dateutil mutagen pycryptodome websockets
    - name: Test building it
      run: yes | python3 -m nuitka --onefile yt_dlp/__main__.py
