name: ytdl-patched build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:

jobs:
  nuitka:
    runs-on: ubuntu-latest
    steps:
    - run: git clone --depth=1 -b ytdlp https://github.com/ytdl-patched/ytdl-patched "$(pwd)"
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -U nuitka zopflipy websockets pyyaml python-dateutil mutagen pycryptodome websockets
    - name: Test building it
      run: nuitka --onefile yt_dlp/__main__.py
