name: ytdl-patched build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: {}

jobs:
  nuitka:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, ubuntu]
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ytdl-patched/ytdl-patched
        ref: ytdlp
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        pip install -U Nuitka zopflipy websockets pyyaml python-dateutil mutagen pycryptodome websockets ordered-set zstandard
    - name: Test building it
      run: yes | python3 -m nuitka --onefile --standalone --low-memory --lto=yes --follow-imports yt_dlp/__main__.py

  pyoxidizer:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, ubuntu]
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ytdl-patched/ytdl-patched
        ref: ytdlp
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        pip install -U pyoxidizer websockets pyyaml python-dateutil mutagen pycryptodome websockets
    - name: Test building it
      run: "true"
