name: yt-dlp ffmpeg detection

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ytdlp: ['2021.10.22', '2021.09.25']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.7.0'
      - name: install yt-dlp
        run: |
          pip install yt-dlp==${{ matrix.ytdlp }}
      - name: download ffmpeg from gyan.dev
        run: |
          curl -o ffmpeg.7z https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z
          7z x ffmpeg.7z
      - name: run PoC
        shell: bash
        run: |
          python3 -c "from yt_dlp import YoutubeDL; ydl = YoutubeDL({'ffmpeg_location': r'ffmpeg-2021-11-03-git-08a501946f-full_build/bin/ffmpeg.exe', 'verbose': True})"
