name: yt-dlp ffmpeg detection

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ytdlp: ['2021.10.22', '2021.09.25']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.7'
      - name: install yt-dlp
        run: |
          pip install yt-dlp==${{ matrix.ytdlp }}
      - name: download ffmpeg from gyan.dev
        run: |
          curl -L -o ffmpeg.7z https://github.com/GyanD/codexffmpeg/releases/download/2021-11-03-git-08a501946f/ffmpeg-2021-11-03-git-08a501946f-full_build.7z
          7z x ffmpeg.7z
      - name: run PoC
        shell: bash
        run: |
          python3 -c "from yt_dlp import YoutubeDL; ydl = YoutubeDL({'ffmpeg_location': r'ffmpeg-2021-11-03-git-08a501946f-full_build/bin/ffmpeg.exe', 'verbose': True})"
